version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15-buster-node-browsers
      - image: progrium/consul
        command: "-server -bootstrap"
      - image: mongo:3.4
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: test

    working_directory: /go/src/github.com/ajvb/kala
    environment:
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"
      MYSQL_DSN: root:@/test

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Waiting for Consul to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 8500 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Consul && exit 1
      - run:
          name: Waiting for Mongo to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mongo && exit 1
      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 15`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1

      - run:
          name: Run unit tests
          command:  go test -v -race ./...

      - run: make bin/kala

      - run:
          name: Start service
          command: ./bin/kala serve --jobdb=consul
          background: true

      - run:
          name: Validate service is working
          command: |
            sleep 5
            curl --retry 10 --retry-delay 1 -X POST --header "Content-Type: application/json" -d '{"command": "echo cool", "name": "test_job"}' http://localhost:8000//api/v1/job/

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
